# PASS-11 Convergence Review — Chapters 15–27 + Back Matter
## Book: "From Token to Fleet" (v20260913-full.pdf, 308pp)
## Scope: convergence pass to confirm zero-new-comments. Source reviewed:
##   design/manuscript/chapter-15.md … chapter-27.md, plus back matter
##   (preface.tex, glossary.tex, sources.tex, references.tex, worksheet.tex).
## Review date: 2026-09-20
## Principle applied: report ONLY genuinely NEW issues not already raised and
##   fixed in PASS-1..10. PASS-1..9 = numeric/cross-ref class; PASS-10 =
##   deep-scale (taxonomy harmonization, ch16 TCO, ch22 [1P]/dup/stale ref,
##   ch20 marginal cost, ch25 activation drift, glossary gaps, [S#] note).
##   Those items are confirmed landed and are NOT re-reported here.

---

## FINDINGS (all genuinely new; none duplicate PASS-1..10)

**Severity: MODERATE | Location: Ch22 §3 Step 1 vs Table 22-1 (chapter-22.md line 21 vs lines 52–53) | Problem:** PASS-10 (P10-M) corrected the canonical input labels from "measured [1P]" to `[canonical scenario][ASSUMPTION]` in §3 Step 1 and claimed Table 22-1 was corrected too. The §3 fix landed, but **Table 22-1 did not fully land**: the "input tokens / request (~9,200)" and "output tokens / request (~300)" rows are still labeled `[ILLUSTRATIVE][DERIVED]` (lines 52–53), while §3 Step 1 states the identical values are `[canonical scenario][ASSUMPTION]` (line 21). Only the "input/output ratio" row (line 54) was updated to `[canonical scenario][DERIVED]`. So within the flagship chapter, the same two values carry two different provenance buckets (`[canonical scenario]` vs `[ILLUSTRATIVE]`) and two different epistemic-status labels (`[ASSUMPTION]` vs `[DERIVED]`). For chosen scenario inputs, status `[DERIVED]` is also the wrong status (a chosen input is an assumption, not a computed quantity). | **Why it matters:** This is precisely the provenance/status axis-conflation the book's evidence discipline exists to prevent, in the chapter the Preface calls the "spine" — and it is a claimed PASS-10 fix that did not fully land. A reader who takes the labels at face value would conclude the canonical 9.2K/300 counts are derived-illustrative scenario inputs in one reading and canonical-scenario assumptions in the same chapter's table. | **Recommended change:** Align Table 22-1's input/output rows to §3: `[canonical scenario][ASSUMPTION]` (or, if the generic-provenance convention is preferred for the table, use `[canonical scenario]` consistently and `[ASSUMPTION]` for chosen inputs across all rows).

**Severity: MINOR | Location: Back matter worksheet.tex (lines 18–19, "All quantities are the architect's own…" parenthetical) | Problem:** The worksheet states the evidence taxonomy in a reduced form — "($[1P]$ first-party, $[2^\circ]$ reputable secondary, with a separate epistemic status of FACT / DERIVED / HYPOTHESIS)" — omitting `[canonical scenario]`, `[LAB]`, and `[ILLUSTRATIVE]` from the provenance axis and `[ASSUMPTION]` and `[UNRESOLVED]` from the status axis. This contradicts the binding taxonomy in both the Preface (preface.tex §"The Architect's Evidence Discipline", lines 114–129) and sources.tex (lines 10–29), which state all five provenance and all five status items. | **Why it matters:** PASS-10 harmonized the taxonomy across Preface, sources.tex, and book-architecture.md, but the worksheet — a published back-matter page the reader fills in — was not part of that harmonization and still advertises a two-item-provenance / three-item-status subset. Crucially, it omits exactly the labels the body uses most on the canonical quantities (`[ILLUSTRATIVE][ASSUMPTION]`), so a reader following the worksheet's "evidence" column would not know those composites exist or are permitted. | **Recommended change:** Make the worksheet's taxonomy parenthetical mirror the full two-axis list from sources.tex (or point to the Sources chapter for the full list), so the fourth published statement of the taxonomy agrees with the other three.

**Severity: MINOR | Location: Ch16 §3 Mode 2 (chapter-16.md line 64) | Problem:** Grammar/article error: "this is *explicitly* a assumed load-duration curve and fast elastically-scalable capacity" — "a assumed" should be "an assumed". | **Why it matters:** Reads as an unedited artifact in a convergence pass meant to reach zero; the same sentence already carries the "explicitly" emphasis intended to flag the assumption, so the article slip stands out. | **Recommended change:** "this is *explicitly* an assumed load-duration curve…".

**Severity: MINOR | Location: Ch17 §1 Concept (chapter-17.md line 9) | Problem:** Grammar: "(b) cross-host communication patterns when a request span multiple machines" — "request span" should be "request spans" (subject–verb agreement). | **Why it matters:** A grammar slip in the chapter's first listing of the fleet model's new ingredients. | **Recommended change:** "when a request spans multiple machines".

**Severity: MINOR | Location: Ch18 §3 Scenario (chapter-18.md line 43) | Problem:** Wording mixes two units: "Total token volume per request: ~9,200 in + ~300 out per hour." The sentence is headed "per request" but appends "per hour", and the 9,200/300 values are per-request token counts, not per-hour volumes. | **Why it matters:** In the chapter's flagship routing arithmetic this blurs request tokens with an hourly volume, which is exactly the token-vs-rate confusion the book warns against; the surrounding §3.3 uses 9,500 tokens/request. | **Recommended change:** "Total token volume per request: ~9,200 in + ~300 out" (drop "per hour"), or state the per-hour volume separately.

**Severity: MINOR | Location: Ch18 §3.3 monthly-savings line (chapter-18.md line 85) | Problem:** "Monthly savings ≈ ($23.75 − $12.59) × 720 hr ≈ $8,100 / month". The savings rate is $11.16/hr (23.75 − 12.59) and $11.16 × 720 = **$8,035**, not $8,100. The stated $8,100 overstates the derived figure by ~$65 (0.8%). | **Why it matters:** A small but genuine within-chapter derivation-vs-claim drift on the chapter's headline saving figure; it does not match the §3.5 "saving ~$11.16/hr" which is correct. | **Recommended change:** "≈ $8,035 / month (≈47% reduction)".

---

## Items checked and found consistent (no action this pass)

- Fleet-sizing arithmetic reconciled end-to-end: C≈18 (437→436 GB ÷ 24.9 GB ≈ 17.5→18), ~2.1 req/s (C/W), λ·W=344 at 40 rps, ~20 hosts (FP16) / ~11 (FP8), and Ch17 Table 17-1 host columns (28/57/32 for 40 rps; 69/141/79 for 100 rps) all recompute correctly.
- Ch17 §8 agentic service-time (W≈13.8 s, 1,380 in-flight at 100 rps, 141 hosts FP16 / 79 FP8) consistent with Ch19's full-service-time scope note; the incremental-orchestration (~660 ms at T=3) vs full-service-time distinction held cleanly.
- Ch19 turn distribution (68/25/5/2), α(1..3)=1.09/1.18/1.27×, expected-input 10,350 / total 10,650, and Table 19-1 columns (10,065…12,960 input; 27.2…34.0 GB KV) all recompute; β≈1.08× correct.
- Ch22 prefill 1.29 PFLOP (2×70B×9.2K=1.288e15), 1.19 PFLOPS required at ~1.08 s, and 5.6 TB/s (140 GB / 25 ms) all verified correct; Fig 22.1 caption distinguishes prefill-per-request from decode-per-token units.
- Ch24 PIES 768 (4×8×6×4), 6.5-host theoretical prefill floor (51.5/7.9) and 16.3 hosts at 40% MFU, and poisoning 52 (1e4×5×0.00104) all recompute correctly; the "missing [FACT]/[DERIVED]/[HYPOTHESIS] axis" is stated explicitly.
- Ch24 §3.3 (prefill-compute floor ~16 hosts at 40% MFU) vs Ch17/20 (KV/latency bound ~20 hosts) are presented as distinct bounds whose max governs — consistent with Ch17's "true answer is the max of the KV bound and the measured throughput bound"; no contradiction.
- Ch25 ADR ~30 GB (per-request working set) vs ~64 GB (runtime/workspace/NCCL reserve) reconciliation and §8 18→33 concurrency (436÷13.4≈32.5) both match the taxonomy/budget; RQO, FSDP, CP, κ, ρ now covered in glossary.
- Ch27 Appendix A: Fig 7.1 GQA cross-reference resolves (fig exists in ch7); KV/FLOP reductions clearly tagged [1P] vendor claims with verify-on-own-hardware caveats; "Observed/Interpretation/Hypothesis" separation is clean.
- Preface (lines 114–129) and sources.tex (lines 10–34) now state identical five-provenance × five-status taxonomies, plus the [S#]-is-not-provenance note — PASS-10 harmonization confirmed landed; no reader-address / "Think of X as Y" constructions found in the reviewed span.

---

## VERDICT
**6 genuinely new findings** (1 MODERATE, 5 MINOR). None duplicate any PASS-1..10 item. The only MODERATE is a claimed-but-incompletely-landed PASS-10 fix: Ch22 Table 22-1's input/output token rows still carry `[ILLUSTRATIVE][DERIVED]` while §3 Step 1 labels the identical values `[canonical scenario][ASSUMPTION]` — an intra-chapter provenance/status inconsistency in the spine chapter. The five MINOR items are: the worksheet.tex reduced-taxonomy statement (fourth place the taxonomy is published, contradicting the harmonized Preface/sources), two article/verb grammar slips (Ch16 "a assumed", Ch17 "a request span"), the Ch18 "per request… per hour" unit mix, and the Ch18 monthly-savings $8,100-vs-$8,035 derivation drift. Convergence is strong: PASS-8=12, PASS-9=11, PASS-10=24 (deep scale), PASS-11=6 — and all 6 are small (one provenance-label residual on the flagship table plus 2 grammar, 1 unit, 1 rounding, 1 taxonomy-consistency item in back matter).
