#!/usr/bin/env python3
"""fig-10-1002: RETIRED — superseded by the three-panel fig-10-1001.

Reviewer demand: the single "composition" canvas (a 2x2 GPU mesh plus a
partitioned/replicated/communication table) put too much into one figure -- the
summary table competed with the topology and the reader had to decode the
patterns from tiny boxes.  Fig 10.1 is now a clean three-panel decomposition
(Panel A tensor / B pipeline / C data) generated by
render/fig_ch10_parallel.py -> design/manuscript/chapter-10/figures/fig-10-1001.{png,pdf}.
The manuscript no longer references fig-10-1002; this generator is kept only as a
signpost and emits nothing, so regen_figs.py cannot resurrect the retired asset.
"""

import sys

print("fig-10-1002 RETIRED: Fig 10.1 is now the three-panel fig-10-1001 "
      "(render/fig_ch10_parallel.py).")
sys.exit(0)
