#!/usr/bin/env python3
"""
harden_kv_svg.py — turn the JS-driven hand-drawn figures (fig-01-kv-cache,
fig-01-token-travel) into STATIC vector SVGs, then render each to a vector PDF
for the LaTeX pipeline.

These figures are generated by gen_fig-01-*.py as HTML that embeds an SVG which
is only finished when rough.js + sketchify.js run in a browser (they turn
`data-rough` elements into real `path`/`rect` shapes).  So until now we had to
ship the browser-rasterised PNG.  This script loads each HTML headlessly in
Chromium, waits for sketchify to finish, and serialises the resolved <svg>
back out — capturing the hand-drawn strokes as genuine vector paths.  It then
writes <name>.svg and uses Inkscape to emit <name>.pdf, so the LaTeX pipeline
can include a true vector figure (and the HTML line can inline the .svg).

Run from repo root:
    python3 render/harden_kv_svg.py
"""
import os
import re
import shutil
import subprocess

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIGDIR = os.path.join(REPO, "design", "manuscript", "chapter-01", "figures")

def find_chrome():
    """Locate a Chromium binary portably: CHROME env override, then on PATH,
    then the playwright-managed build. No hard-coded user/machine paths."""
    cand = os.environ.get("CHROME") or shutil.which("chromium") or shutil.which("google-chrome")
    if cand:
        return cand
    # last resort: discover the playwright chromium install without assuming a
    # username or a specific browser build number
    for base in (os.path.expanduser("~/.cache/ms-playwright"),
                 os.environ.get("PLAYWRIGHT_BROWSERS_PATH", "")):
        if not base or not os.path.isdir(base):
            continue
        for d in sorted(os.listdir(base), reverse=True):
            exe = os.path.join(base, d, "chrome-linux", "chrome")
            if os.path.exists(exe):
                return exe
    return "chromium"

CHROME = find_chrome()

TARGETS = ["fig-01-kv-cache", "fig-01-token-travel"]


def headless_svg(html_path):
    url = "file://" + html_path
    r = subprocess.run(
        [CHROME, "--headless=new", "--disable-gpu", "--no-sandbox",
         "--virtual-time-budget=5000", "--dump-dom", url],
        capture_output=True, text=True, timeout=90,
    )
    dom = r.stdout
    i = dom.find("<svg")
    j = dom.rfind("</svg>")
    if i == -1 or j == -1:
        raise RuntimeError(f"no svg found in {html_path} (exit {r.returncode})")
    svg = dom[i:j + 6]
    # drop width/height attrs so it scales to any box; keep viewBox
    svg = re.sub(r' width="[^"]*" height="[^"]*"', "", svg, count=1)
    # Chromium's --dump-dom serialisation drops the XML namespace on the
    # <svg> root, AND drops the <style> block that defined the figures' CSS
    # classes.  Without xmlns a data-URI SVG embedded in an <img> fails to
    # render at all (broken-image icon); without the class definitions the
    # hand-drawn figures' styled <text> falls back to defaults.  Re-inject
    # both so the hardened SVG is fully self-contained.
    if "xmlns=" not in svg.split("<svg", 1)[1][:120]:
        svg = svg.replace("<svg ", '<svg xmlns="http://www.w3.org/2000/svg" ', 1)
    if "mono" in svg or "t-title" in svg:
        style = '<style>.t-title{font-weight:700;}.mono{font-family:ui-monospace,Menlo,Consolas,monospace;}</style>'
        svg = svg.replace(">", ">" + style, 1)
    return svg


def main():
    # CSS colour variables defined in each gen HTML's <style>; after serialising
    # the SVG we lose the <style>, so bare `var(--ink)`/`var(--paper)` would
    # render black/transparent (exactly the black-background bug reported).
    # Resolve them to concrete values so the figure always has an explicit,
    # light background regardless of renderer.
    VAR_MAP = {
        "var(--paper)": "#f8f5e8",  # light paper
        "var(--ink)": "#212020",    # near-black ink for lines/text
    }
    for name in TARGETS:
        html = os.path.join(FIGDIR, f"{name}.html")
        if not os.path.exists(html):
            print("skip (no html):", name)
            continue
        svg = headless_svg(html)
        n_path = len(re.findall(r"<path", svg))
        for var, val in VAR_MAP.items():
            svg = svg.replace(var, val)
        # safety: also inject a style block in case any other var survives
        if "var(--" in svg:
            svg = svg.replace("<svg ", "<svg style=\"--paper:#f8f5e8;--ink:#212020;\" ", 1)
        svg_path = os.path.join(FIGDIR, f"{name}.svg")
        open(svg_path, "w", encoding="utf-8").write(svg)
        # Inkscape: SVG -> vector PDF
        pdf_path = os.path.join(FIGDIR, f"{name}.pdf")
        subprocess.run(["inkscape", svg_path, "--export-filename=" + pdf_path,
                        "--export-type=pdf", "--without-gui"],
                       capture_output=True, text=True, timeout=120)
        print(f"{name}: svg {os.path.getsize(svg_path)/1024:.0f}KB "
              f"({n_path} paths), pdf {os.path.getsize(pdf_path)/1024:.0f}KB")
    print("DONE")


if __name__ == "__main__":
    main()
